name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get nightly Rust
      run: rustup toolchain install nightly
    - name: Clippy check
      run: cargo +nightly clippy; cd fx-maths; cargo +nightly clippy; cd ..
    - name: Build
      run: cargo +nightly build -r -j8
    - name: Run tests
      run: cd fx-maths; cargo +nightly test
